# generated by zon2nix (https://github.com/Cloudef/zig2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:
with builtins;
with lib; let
  unpackZigArtifact = {
    name,
    artifact,
  }:
    runCommandLocal name {nativeBuildInputs = [zig];} ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig = {
    name,
    url,
    hash,
  }: let
    artifact = fetchurl {inherit url hash;};
  in
    unpackZigArtifact {inherit name artifact;};

  fetchGitZig = {
    name,
    url,
    hash,
    rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
  }: let
    parts = splitString "#" url;
    url_base = elemAt parts 0;
    url_without_query = elemAt (splitString "?" url_base) 0;
  in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact = {
    name,
    url,
    hash,
    ...
  } @ args: let
    parts = splitString "://" url;
    proto = elemAt parts 0;
    path = elemAt parts 1;
    fetcher = {
      "git+http" = fetchGitZig (
        args
        // {
          url = "http://${path}";
        }
      );
      "git+https" = fetchGitZig (
        args
        // {
          url = "https://${path}";
        }
      );
      http = fetchZig {
        inherit name hash;
        url = "http://${path}";
      };
      https = fetchZig {
        inherit name hash;
        url = "https://${path}";
      };
    };
  in
    fetcher.${proto};
in
  linkFarm name [
    {
      name = "N-V-__8AACbncwDdHLMz3EkS8iDHirtmHehU_FWTuKnmd9ik";
      path = fetchZigArtifact {
        name = "imgui";
        url = "git+https://github.com/ocornut/imgui.git?ref=v1.91.9b-docking#4806a1924ff6181180bf5e4b8b79ab4394118875";
        hash = "sha256-mQOJ6jCN+7VopgZ61yzaCnt4R1QLrW7+47xxMhFRHLQ=";
        rev = "4806a1924ff6181180bf5e4b8b79ab4394118875";
      };
    }
    {
      name = "capstone-6.0.0-Alpha4-tmNUgdI8AADDVL-qUUVmU0IGuFGpjz6-O7sBRjeB53yb";
      path = fetchZigArtifact {
        name = "capstone";
        url = "git+https://github.com/allyourcodebase/capstone.git#ece2cef731de80b6a2d2beb461024196c8dfee9d";
        hash = "sha256-jqYbCviAAmW8XL45zpTKYKrupsa315KP0DGxVSgtqxE=";
        rev = "ece2cef731de80b6a2d2beb461024196c8dfee9d";
      };
    }
    {
      name = "N-V-__8AAHAJ7QVuN5ADQLFxagK0PhxnQw9kUCjUDjFpjLbD";
      path = fetchZigArtifact {
        name = "capstone";
        url = "https://github.com/capstone-engine/capstone/archive/refs/tags/6.0.0-Alpha4.tar.gz";
        hash = "sha256-rzCjSvQVEjGXsoByr6qeD9LEyQ2vcFKMvNE9VXfnoow=";
      };
    }
    {
      name = "N-V-__8AALwkAAB_H_lRcdLYz-_DCoAy71ze0CtKLsHdDRD-";
      path = fetchZigArtifact {
        name = "ini";
        url = "git+https://github.com/rxi/ini.git#13a254c9e38def8924a83badfea5eda5a01b9295";
        hash = "sha256-Eb/2Sfzyoo8Rpk6UoSoY5uDFxyd8Ar4E876O9JNfZ3Q=";
        rev = "13a254c9e38def8924a83badfea5eda5a01b9295";
      };
    }
    {
      name = "nativefiledialog_extended-1.2.1-2-_pDry5gcAAA701XtymPdScWmrLQ5Zuw9yZYm_bxp7DkQ";
      path = fetchZigArtifact {
        name = "nativefiledialog_extended";
        url = "git+https://github.com/allyourcodebase/nativefiledialog-extended.git?ref=1.2.1-2#dd47ba4b99b85c78f30a8faca0518ed913268c0a";
        hash = "sha256-S0AvXFtA82PJ4a9L+ES6Zvqux5Bz+urwBhjUcfqCkaQ=";
        rev = "dd47ba4b99b85c78f30a8faca0518ed913268c0a";
      };
    }
    {
      name = "N-V-__8AAN9tCgD3-w1k2cbga_852Tq67XM6_vfGQoHt_T5D";
      path = fetchZigArtifact {
        name = "nativefiledialog-extended";
        url = "git+https://github.com/btzy/nativefiledialog-extended.git?ref=v1.2.1#86d5f2005fe1c00747348a12070fec493ea2407e";
        hash = "sha256-GwT42lMZAAKSJpUJE6MYOpSLKUD5o9nSe9lcsoeXgJY=";
        rev = "86d5f2005fe1c00747348a12070fec493ea2407e";
      };
    }
    {
      name = "N-V-__8AAEi9BgBKV3vzD6pzRAbfs1f7lNp1wsrArxR79lx6";
      path = fetchZigArtifact {
        name = "rpmalloc";
        url = "git+https://github.com/mjansson/rpmalloc.git?ref=1.4.5#e4393ff85585d91400bcbad2e7266c011075b673";
        hash = "sha256-dE6shh2F3a+pu510Vw9icQvk2aAoPWYCtrIlT08fF3A=";
        rev = "e4393ff85585d91400bcbad2e7266c011075b673";
      };
    }
    {
      name = "N-V-__8AAJKtAACXam4qGbql--FmlkH5sGRDUY6n_tqMfZW-";
      path = fetchZigArtifact {
        name = "getopt_port";
        url = "git+https://github.com/kimgr/getopt_port.git#9d3d387087d252970923db7f297f681622c4e026";
        hash = "sha256-k8BXLDC4tup83BwU/UQ5PG2yFPiN7boInm1x6MizGYQ=";
        rev = "9d3d387087d252970923db7f297f681622c4e026";
      };
    }
    {
      name = "N-V-__8AADb7TQBhnAapR8-szphSk_8WmU22BY8jadPC_8-d";
      path = fetchZigArtifact {
        name = "stb";
        url = "git+https://github.com/nothings/stb.git#ae721c50eaf761660b4f90cc590453cdb0c2acd0";
        hash = "sha256-BIhbhXV7q5vodJ3N14vN9mEVwqrP6z9zqEEQrfLPzvI=";
        rev = "ae721c50eaf761660b4f90cc590453cdb0c2acd0";
      };
    }
    {
      name = "N-V-__8AAKQTAgC4IUwwDQSA3kMErF_02NAb-DgnNFymn_wr";
      path = fetchZigArtifact {
        name = "dtl";
        url = "git+https://github.com/cubicdaiya/dtl.git?ref=v1.21#32567bb9ec704f09040fb1ed7431a3d967e3df03";
        hash = "sha256-s+syRiJhcxvmE0FBcbCi6DrL1hwu+0IJNMgg5Tldsv4=";
        rev = "32567bb9ec704f09040fb1ed7431a3d967e3df03";
      };
    }
    {
      name = "N-V-__8AAPwi1QA62l3pm0hnYBnFKtjqBqXK50MZxfH-Wq8C";
      path = fetchZigArtifact {
        name = "nlohmann_json";
        url = "git+https://github.com/nlohmann/json.git?ref=v3.11.3#9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03";
        hash = "sha256-7F0Jon+1oWL7uqet5i1IgHX0fUw/+z0QwEcA3zs5xHg=";
        rev = "9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03";
      };
    }
    {
      name = "N-V-__8AAJ7xAABXU9I52yQSQ-zeeJEohtrHKj9ekUVZdlOR";
      path = fetchZigArtifact {
        name = "pdqsort";
        url = "git+https://github.com/orlp/pdqsort.git#b1ef26a55cdb60d236a5cb199c4234c704f46726";
        hash = "sha256-xn3Jjn/jxJBckpg1Tx3HHVAWYPVTFMiDFiYgB2WX7Sc=";
        rev = "b1ef26a55cdb60d236a5cb199c4234c704f46726";
      };
    }
    {
      name = "N-V-__8AALk1AwB_-PJsG-Q9F1OHqaGovuaHaqFCkhppJHXw";
      path = fetchZigArtifact {
        name = "ppqsort";
        url = "git+https://github.com/GabTux/PPQSort.git?ref=v1.0.5#249da1c63b06824befc4ed643b883328cfdd6ba0";
        hash = "sha256-EMZVI/uyzwX5637/rdZuMZoql5FTrsx0ESJMdLVDmfk=";
        rev = "249da1c63b06824befc4ed643b883328cfdd6ba0";
      };
    }
    {
      name = "N-V-__8AAMC4CwDqHbQUv2a4lEr_UXtrXeW5CWU6X3mzDLo6";
      path = fetchZigArtifact {
        name = "robin_hood_hashing";
        url = "git+https://github.com/martinus/robin-hood-hashing.git#7697343363af4cc3f42cab17be49e6af9ab181e2";
        hash = "sha256-17Mec4DC+BxgBVQSSxWldek7lDKCQ2Cmkjh7DKzppBk=";
        rev = "7697343363af4cc3f42cab17be49e6af9ab181e2";
      };
    }
    {
      name = "N-V-__8AAGS5UgB9tuEDsjOj_PBuqhvifei8hQNtCQwmN6g4";
      path = fetchZigArtifact {
        name = "xxHash";
        url = "git+https://github.com/Cyan4973/xxHash.git#a57f6cce2698049863af8c25787084ae0489d849";
        hash = "sha256-JlYhbyYvB7NnP/GaAjry4wro65bT32Lx6Isawi3YwNw=";
        rev = "a57f6cce2698049863af8c25787084ae0489d849";
      };
    }
  ]
